DROP TABLE IF EXISTS AuditedTable;

DROP TABLE IF EXISTS ReadOnlyTable;

CREATE TABLE IF NOT EXISTS AuditedTable (
       ID bigint generated by default as identity,
        CREATED_USER varchar(255),
        CREATED_DATE timestamp,
        DELETED_DATE timestamp,
        DELETED boolean,
        UPDATED_BY varchar(255),
        UPDATED_DATE timestamp,
        TestColumn varchar(255),
        primary key (ID)
    );
    
CREATE TABLE IF NOT EXISTS ReadOnlyTable (
       ID bigint generated by default as identity,
        TestColumn varchar(255),
        primary key (ID)
    );
    
merge into ReadOnlyTable  KEY(ID)
VALUES (1, 'Test Val');
